baseURL: ""
languageCode: "en-us"
title: "Harshitha Chegu"
theme: hugo-profile

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
     # name: Blog
      title: Blog posts
      url: /blogs
      weight: 1
    - identifier: gallery
     # name: Gallery
      title: Blog posts
      url: /gallery
      weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  # title: "Hugo Profile"
  # description: Text about my cool site
  # # staticPath: ""  # The path to serve the static files from
  # favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  #useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    #  # Show brand logo in nav bar | default is true
    #brandName: "Hugo" # Brand name for the brand | default is the title variable
    #searchPlaceholder: "Search"
    brandLogo: ""
    disableSearch: true
    showBrandLogo: false
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: true
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi there! I'm"
    title: "Harshitha Chegu"
    #subtitle: "bondam antara babu"
    content: "A highly organized and hardworking individual searching for a position to secure a challenging and responsible career opportunity to expand my learnings, knowledge, skills and contribute to the field."
    image: /images/Prof1.jpg
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: https://drive.google.com/file/d/1DJQrFImM83Gd8pSKezvVMTu9Zg2SWKUr/view?usp=sharing
      download: false
      newPage: true
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/CHEGU-HARSHITHA
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/harshitha-gupta/
      customIcons:
        #- icon: /fav.png
        #  url: "https://example.com"

  # About
  about:
    enable: true
    title: "I am open to work from December 2023"
    image: /images/Prof2.jpg
    content: |-

    skills:
      enable: true
      title: "A master's student majoring in data science with over three years of hands-on experience in Python, R, SQL, and Machine Learning. I possess a profound interest in data-driven decision-making and a steadfast commitment to leveraging data for actionable insights"
      items:
        - "Python, R, SQL, NoSQL, Machine Learning, Tableau, AWS"
        - "Mentorship, Communication, Collaboration, Time Management, Team Player"
        # - "JavaScript"

  # Experience
  experience:
    enable: true
    #title: "Custom Name"
    items:

      - job: "Data Science Analyst Intern"
        company: "KMap - UoA"
        companyUrl: "https://kmap.arizona.edu/"
        date: "May 2023 - present"
        info:
          enable: true
        featuredLink:
          enable: false
          # name: "View the project"
          # url: "https://example.com"
        content: |-
          Tucson, AZ

          - Perform data preprocessing, develop a language-based model using OpenAI to generate research topic predictions, achieving
          - improved accuracy in identifying and categorizing topics within large textual datasets
          - Establish knowledge graphs and networks, facilitating interdisciplinary collaborations within specific research domains
          - Identify and solve data problems by performing root cause analysis, resulting in the improved accuracy and reliability of datadriven decisions
          - Create datasets by pulling data from APIs using Python scripts, resulting in the creation of clean, usable datasets
          - Manage projects using Jira, tracking tickets and issues to ensure timely completion
          - Conduct code reviews following best practices to identify potential errors and improve code quality
          - Perform A/B testing to improve website conversion rates, resulting in a 10% increase in conversions 


      - job: "Data Analyst"
        company: "KMap - UoA"
        companyUrl: "https://kmap.arizona.edu/"
        date: "Jan 2023 - May 2023"
        info:
          enable: true
        featuredLink:
          enable: false
          # url: "https://example.com"
        content: |-
          Tucson, AZ

          - Developed Python scripts to implement data cleaning on 100K+ rows on large-scale datasets to deliver accurate results
          - Leveraged ETL to extract data from various sources using web scraping, transform it, and store the collections in MongoDB
          - Optimized SEO strategies using MongoDB Atlas, enhancing user experience and boosting website ranking by 17%
          - Delivered technical workshops to non-technical audiences using presentations, improving understanding of platform
          - Managed code documentation and ensured codebase integrity through effective use of Git version control
          - Developed visualizations and dashboards using Power bi to communicate findings and facilitated discussions with team members to identify actionable insights and make data-driven decisions
      
      
      - job: "Web development Intern"
        company: "Creatick Solutions"
        companyUrl: "https://www.creaticksolutions.com/"
        date: "Nov 2018 - May 2019"
        info:
          enable: true
        featuredLink:
          enable: false
          # url: "https://example.com"
        content: |-
          Hyderabad, India

          - Designed and coordinated the development of a comprehensive Adventure Catalog website using HTML, CSS and WordPress
          - Streamlined adventure site data by collecting over 50 well-known sites using SQL to integrate detailed adventure information 


  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Masters in Data Science"
        school:
          name: "University of Arizona, Tucson"
          url: "https://www.arizona.edu/"
        date: "2022 - 2023"
        GPA: "4.0 out of 4.0"
        content: |-
            - Actively engaged in group discussions, contributing to insightful exchanges of ideas
            - Delivered presentations, enhancing communication skills and the ability to convey complex concepts
            - Collaborated effectively in various team projects, demonstrating strong teamwork and adaptability
            - Participated in code reviews to maintain high coding standards and project integrity during coding assignments
            - Attending GHC 2023

            Course Work 
              - Natural Language Processing (NLP), Data Warehousing and Cloud, Machine Learning, Data Mining, Data Visualization, Artificial Intelligence , Ethical Issues in Information

      - title: "Bachelor of Technology in Computer Science"
        school:
          name: "Malla Reddy College of Engineering"
          url: "https://www.mrce.in/"
        date: "2019 - 2022"
        GPA: "7.6 out of 10"
        content: |-
          - Led a team of three members in the successful execution of two final projects, demonstrating effective leadership and project management skills
          - Data Science Course Work: Python, SQL, Database Management Systems, Machine Learning, Computer Oriented Statistical Methods, Discrete Mathematics, Data Mining, Cloud Computing
          - Computer Science Course Work: Cryptography and Network Security, Compiler Design, Design and Analysis of Algorithms, Network Programming, Automata Theory, Computer Graphics, Computer Networks, Operating Systems, Data Structures
          - Software Management Courses: Software Engineering, Software Process and Project Management, Web Development
          - Other Course Work: Business Economics and Financial Analysis, Environmental Science, Advanced Communication Skills

        featuredLink:
          enable: false
          name: "My academic record"
          url: "https://example.com"
      # - title: "High School"
      #   school:
      #     name: "Thomas Jefferson High School for Science and Technology."
      #     url: "https://example.org"
      #   GPA: "4.2 out of 5.0"
      #   featuredLink:
      #     enable: true
      #     url: "https://example.com"

  # Achievements
  achievements:
    enable: false
    # title: "Custom Name"
    items:
      - title: Google kickstart runner
        content: I solved all problems with optimal solution.
        url: https://example.com
        image: /images/achievment.jpg
      - title: Facebook Hackathon Winner
        content: Developed a product using Artificial Intelligence.
        image: /images/achievment.jpg
      - title: Hugo Profile
        content: Developed a theme and getting 1K+ downloads per month.
        url: "https://github.com/gurusabarish/hugo-profile"
        image: /images/achievment.jpg
      - title: Microsoft Imagine Runner
        content: We are developed a product which can help others.
      - title: Google Summer of Code
        content: Contributed to a open source project.
        url: https://example.com

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: Prediction and Analysis of Click Through Rate
        content: A Machine Learning based application that predicts how often people click on online ads
        image: images/CTR.jpg
        # featured:
        #   name: Click here to know more!
        #   link: https://github.com/CHEGU-HARSHITHA/Prediction-and-Analysis-of-Click-Through-Rate 
        # badges:
        #   - "Supervised Machine Learning"
        #   - "Python"
        links:
          - icon: fab fa-github
            url: https://github.com/CHEGU-HARSHITHA/Prediction-and-Analysis-of-Click-Through-Rate 

      - title: Cluster Analysis on Spotify Dataset
        content: Conducted cluster analysis on Spotify dataset, extracting insights into user music preferences
        image: /images/spotify.png
        # featured:
        #   name: Demo V2
        #   link: 
        # badges:
        #   - "Unsupervised Machine Learning"
        #   - "R"
        #   - "Tableau"
        links:
          - icon: fab fa-github
            url: https://github.com/CHEGU-HARSHITHA/Cluster-Analysis-on-Spotify-dataset 
            
      - title: Earthquake Damage Predictor
        content: Developed a model for predicting earthquake damage levels, aiding in disaster preparedness and response
        image: /images/earthquake.jpg
        # featured:
        #   name: Click here to know more!
        #   link: 
        #  badges:
        #    - "Supervised Machine Learning"
        #    - "Python"
        # links:
        #   - icon: fab fa-github
        #     url: https://github.com/gurusabarish/hugo-profile

      - title: Detection of fraudulent behavior in Water consumption
        content: Analyzed data and Created techniques for identifying fraudulent water consumption patterns
        image: /images/waterconsumption.jpg
        # featured:
        #   name: Demo
        #   link: 
        # badges:
        #   - "Machine Learning"
        #   - "Python"
        #   - "SQL"
        # links:
        #   - icon: fab fa-github
        #     url: https://github.com/gurusabarish/converter

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, Iâ€™ll try my best to get back to you!
    email: chharshithagupta@gmail.com
    btnName: Mail me
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/CHEGU-HARSHITHA
      linkedin: https://www.linkedin.com/in/harshitha-gupta/
      #twitter: https://twitter.com
      #instagram: https://instagram.com
      #facebook: https://facebook.com

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  # terms:
  #   read: "Read"
  #   toc: "Table Of Contents"
  #   copyright: "All rights reserved"
  #   pageNotFound: "Page not found"
  #   emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
